spring.application.name: MapMatcher

server:
    port: 8080

graphhopper:
    osmdata:
        location: etc/map-data/osm-data.osm.pbf

barefoot:
    matcher:
        sigma: 45
        lambda: 0.1
        maxradius: 75
        maxdistance: 1000 
        mindistance: 20
        mininterval: 5000
    postgis:
        host: localhost
        port: 5432
        database: osmdata
        table: bfmap_ways
        user: postgres
        pass: postgres
    routetype: etc/map-data/road-types.json