spring.application.name: MapMatcher

server:
    port: 8080

graphhopper:
    osmdata:
        location: etc/map-data/muenster-regbez-latest.osm.pbf

barefoot:
    postgis:
        host: mapserver
        port: 5432
        database: nrw
        table: bfmap_ways
        user: osmuser
        pass: pass