spring:
    application:
        name: MapMatcher
    profiles:
        active: barefoot

server:
    port: 8081

---

spring:
    profiles: graphhopper

graphhopper:
    matcher:
        default_sigma: 45
        default_beta: 2.0
    osmdata:
        location: ../etc/map-data/osm-data.osm.pbf

---

spring:
    profiles: barefoot
    
barefoot:
    matcher:
        sigma: 45
        lambda: 0.1
        maxradius: 75
        maxdistance: 1000 
        mindistance: 20
        mininterval: 5000
        costfunction: distance
    postgis:
        host: 172.17.0.2
        port: 5432
        database: gis
        table: planet_osm_line
        user: postgres
        pass: postgres
    routetype: etc/map-data/road-types.json
    
--- 

spring:
    profiles: valhalla
    
valhalla:
    service:
        url: http://localhost:8002
        
---

spring:
    profiles: mapbox

mapbox:
    matcher:
        pagelimit: 100
        pageoverlap: 5